### ISSUE TITLE
Unexpected old RSS item appears as latest on Triunfo CSE

### ISSUE THREAD

**Issue by elbidone** [meumobi/sitebuilder#80]
Bugs on RSS continue...

![img_0010_png](https://cloud.githubusercontent.com/assets/9011612/7628157/10477908-f9f6-11e4-8f22-ebc44ea01676.png)

**Comment by elbidone** [comment]
The non expected record is updated at each importation, id and order are renewed

I've tested the importation of same feed on INT, it raises exactly the same issue

```
> db.items.find({'_id': ObjectId("55545615701796c46a8b4663")})
{ "_id" : ObjectId("55545615701796c46a8b4663"), "order" : 6897, "created" : ISODate("2014-08-13T13:00:00Z"), "modified" : ISODate("2015-05-14T08:00:21.664Z"), "published" : ISODate("2015-05-14T08:00:21.662Z"), "is_published" : true, "thumbnails" : [ ], "groups" : [ ], "guid" : "http://ri.triunfo.com/Show.aspx?idMateria=ZP4dprUSPxm1VDe7U8vr1A==", "link" : "http://ri.triunfo.com/Show.aspx?idMateria=ZP4dprUSPxm1VDe7U8vr1A==", "pubdate" : ISODate("2014-08-13T13:00:00Z"), "description" : "<center>\n\t<div align=\"center\">\n\t\t<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"620\"><tbody>\n<tr>\n<td align=\"center\" height=\"10\" valign=\"bottom\">\n\t\t\t\t\t\t </td>\n\t\t\t\t</tr>\n<tr>\n<td align=\"center\" valign=\"top\">\n\t\t\t\t\t\t<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"><tbody><tr>\n<td align=\"left\" bgcolor=\"#FFFFFF\" height=\"45\" valign=\"top\">\n\t\t\t\t\t\t\t\t\t\t<center>\n\t\t\t\t\t\t\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"551\"><tbody>\n<tr>\n<td width=\"551\">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span>COMUNICADO AO MERCADO</span></p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n<tr>\n<td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span><u>COMPLEMENTO </u>- REAJUSTE DAS TARIFAS DE PEDÁGIO DA CONCER</span></p>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n<tr>\n<td height=\"24\" valign=\"top\">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span>Em complemento ao Comunicado ao Mercado divulgado em 11 de agosto de 2014, a respeito da revisão tarifária da Concessão Rodoviária Juiz de Fora – Rio S.A. – Concer, a Triunfo Participações e Investimentos S.A. informa que:</span>\n</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span>O aumento de 12,50% é composto por 5,29% referente à compensação de metade da perda de tráfego ocorrido pela mudança da praça de pedágio do km 104 para o km 102 e por 6,52% referente ao reajuste anual pela variação do IPCA. A compensação pela segunda metade da parcela da perda de tráfego será efetuada a partir de agosto de 2015, na próxima revisão tarifária. </span>\n</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span><a height=\"85px\" href=\"https://workflow.comunique-se.com.br//Download.aspx?Arquivo=gXmMYymN2vDSmRimGZB99g==\" target=\"_blank\" width=\"100px\">Clique aqui </a>para o arquivo em PDF.</span>\n</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n</tbody></table>\n</center>\n\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t</tr></tbody></table>\n</td>\n\t\t\t\t</tr>\n<tr>\n<td align=\"center\" bgcolor=\"#f0efe8\" valign=\"top\">\n\t\t\t\t\t\t </td>\n\t\t\t\t</tr>\n<tr>\n<td align=\"center\" valign=\"top\">\n\t\t\t\t\t\t<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"><tbody></tbody></table>\n</td>\n\t\t\t\t</tr>\n</tbody></table>\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"><tbody><tr>\n<td align=\"right\" height=\"30\" valign=\"bottom\">\n\t\t\t\t\t\t<a href=\"http://riweb.com.br/\" title=\"RIWEB\"><img border=\"0\" src=\"http://template.comunique-se.com.br/lopes/mkt/img/logo_riweb.gif\"></a>\n</td>\n\t\t\t\t</tr></tbody></table>\n<br>\n\t\t </div>\n</center>\n<p>\n\t </p>\n", "author" : "", "medias" : [ 	{ 	"url" : "http://ri.triunfo.com/Download.aspx?Arquivo=gXmMYymN2vDSmRimGZB99g==", 	"type" : "application/pdf", 	"title" : "ComunicadoMercado - 140811 - Reajuste Concer_vreap", 	"length" : 77, 	"thumbnails" : [ ] } ], "site_id" : 10, "parent_id" : 94, "title" : "Comunicado ao Mercado - Complemento ao Reajuste das Tarifas de Pedágio da Concer", "format" : "html", "type" : "articles" }
>
```

**Comment by elbidone** [comment]
The unexpected latest item is exactly the 50th on RSS (order of appearance), and we save the only 50 first. But instead of having the lower order of the 50, it has the higher.

**Comment by elbidone** [comment]
On 1st import the order is respected, it seems that the bug occurs with the 50th element after the 1st import

**Comment by elbidone** [comment]
![painel_de_controle___meumobi_investors](https://cloud.githubusercontent.com/assets/9011612/7668312/e2a1b220-fc07-11e4-96a7-597f4e89ecc9.png)

**Comment by elbidone** [comment]
I think I've found the origin of issue. It occurs only on articles that appears on various feeds url using same guid. For example on both following feeds the same news about "Viracopos" is available with same guid http://ri.triunfo.com/Show.aspx?idMateria=oYFnhT7yR2I5lfX7mehNNQ==.

To fix it we could define a primary key for items from feed as extension_id+guid or category_id+guid

**Comment by juliogreff** [comment]
I could not reproduce the issue locally (and I'm afraid to test this in production since I don't know what to do if the issue is not fixed), but I believe I know the cause of the issue.

First, I don't believe it's the same article appearing in more than one feed, since we already have a composite primary key in place, and all operations respect that.

What I found though, is that Triunfo's feeds keep the entire backlog (200+ items right now), and we process all of them every time. That means we save 200+ articles, and then prune it to 50. I fixed it, so now we only process the 50 most recent articles.

Contact me ASAP so we can test this together and see if the problem is really fixed.

**Comment by juliogreff** [comment]
I also realized that saving and deleting records like this generates a lot of fragmentation, and this might be the reason mongodb is using so much space and creating new files.

**Comment by elbidone** [comment]
It occured on INT, I've tested earlier with last deploy current -> /home/meumobi/PROJECTS/int-meumobi.com/releases/20150517115919 and it seems to be fixed
I'll monitoring it today and if fine we'll do deploy on CSE tomorrow

**Comment by elbidone** [comment]
I'm testing on INT adding items on feed

**Comment by elbidone** [comment]
It raises another bug, now the latest item has the lowest order instead of highest. Please test!! if you call the api you'll see that the first items retrieved are the oldest:
http://int-meumobi.com/api/feedrunner.int-meumobi.com/categories/54/items

**Comment by juliogreff** [comment]
I did not remove all items before reprocessing them again, so this is why I didn't see this issue. It is now fixed.

To me, there's a big problem that we rely in the "order" attribute for feeds, since it is very sensitive to the order the items are inserted (if the items in the feed were not in order, or in reverse order, for example, the issue would appear again). This is also why we saw very old items at the top instead of the bottom as well (if we relied on the pubdate, there would still be a bug, but it wouldn't be as critical).

In the future, we might have an option per category to sort items either by order or by creation/publication date.

**Comment by elbidone** [comment]
On [rss-profile] it's explained that order no matter
> The order of elements within the channel MUST NOT be treated as significant.

But we should use order field to be compliant with item interface. I agree that the order could consider the pubdate and not the order on channel element. Don't think necessary to provide the option of order.

[rss-profile]: http://www.rssboard.org/rss-profile

**Comment by t4deu** [comment]
The issue is not fixed:
category url: http://triunfopt.int-meumobilesite.com/#/articles/94
feed url: http://ri.triunfo.com/FeedMeuMobi.aspx?idCanal=SSTlMgk6MBpj8Lh8VGrutw==
